# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('car_partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_fuel', models.FloatField()),
                ('delegation_starting', unixtimestampfield.fields.UnixTimeStampField()),
                ('delegation_ending', unixtimestampfield.fields.UnixTimeStampField()),
                ('driver', models.CharField(max_length=160)),
                ('owner', models.CharField(max_length=160)),
                ('type', models.CharField(max_length=20)),
                ('created_at', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('modified_at', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('deleted_at', unixtimestampfield.fields.UnixTimeStampField(blank=True)),
                ('partners', models.ManyToManyField(to='car_partner.Partner')),
            ],
        ),
    ]
