# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-06 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('car_partner', '0002_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='deleted_at',
            field=unixtimestampfield.fields.UnixTimeStampField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='partners',
            field=models.ManyToManyField(blank=True, to='car_partner.Partner'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='deleted_at',
            field=unixtimestampfield.fields.UnixTimeStampField(blank=True, null=True),
        ),
    ]
