# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-07 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_partner', '0003_auto_20191106_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
