# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-07 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_partner', '0004_auto_20191107_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='partners',
            field=models.ManyToManyField(blank=True, editable=False, related_name='cars_set', to='car_partner.Partner'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
