version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_DB: car_partner_registry
      POSTGRES_PASS: 1234
    volumes:
      - pgdata:/var/lib/posgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata: